name: Kyle Keesling
description: An Indianpolis-based Pixel Pusher
url: http://kyleke.es
timezone: America/Indianapolis


permalink: /:year/:month/:title
paginate: 10

markdown: redcarpet
markdown_ext:  markdown,mkd,mkdn,md

pygments: true
