name: Kyle Keesling
description: An Indianpolis-based Pixel Pusher
title: Kyle Keesling - An Indianpolis-based Pixel Pusher
url: https://kylekeesling.dev
timezone: America/Indianapolis

permalink: /posts/:year/:month/:title

paginate: 10
paginate_path: page:num

markdown: kramdown #redcarpet
markdown_ext:  markdown,mkd,mkdn,md
highlighter: rouge

include: [".well-known"]
